uma-rs : fixed class case exception
java.lang.ClassCastException: org.jboss.resteasy.specimpl.BuiltResponse cannot be cast to org.jboss.resteasy.core.ServerResponse
        at org.xdi.oxd.rs.protect.resteasy.RptPreProcessInterceptor.preProcess(RptPreProcessInterceptor.java:86)
        at org.xdi.oxd.licenser.server.ws.UmaProtector.preProcess(UmaProtector.java:140)
        at org.jboss.resteasy.core.interception.ContainerRequestFilterRegistry$ContainerRequestFilterFacade.filter(ContainerRequestFilterRegistry.java:46)

(cherry picked from commit 3d47769)